### PR TITLE
Add additional CA certificates to /etc/rancher/ssl

### PR DESCRIPTION
**Pull request by superseb**
https://github.com/rancher/rancher/issues/16086

Quickest way to solve current broken functionality, this probably needs a refactor after fixing to see if it can be made better.

### CODE REVIEW

**Comment by alena1108** [comment]
@superseb @jgreat we might need to change the base branch to alpha as the fix is targeted rancher 2.2

**Comment by jgreat** [comment]
This worked when the functionality was added in 2.0.8, did something change?  This is the default path for ssl certs in the debian image.

**Comment by superseb** [comment]
Can you share how you tested it so it can be compared against the filed issue?

**Comment by jgreat** [comment]
Looks like adding in https://github.com/rancher/rancher/blob/32e12d5e1a418f917dc9b170e3354bf4e28c803b/package/Dockerfile#L58 changed the default system path for CA certs. This was added in the 2.1.0 release.

**Review by jgreat — APPROVED** [review]

**Comment by jgreat** [comment]
Tested changes with a MITM proxy.  Rancher finds the additional-ca.pem with the new path.

**Pull request merged**
